// ---------------------------------------------------------------------------
// CourtSync — Bookings & Calendar Domain Constants & Data Definitions
// ---------------------------------------------------------------------------

export const formatTime12 = (timeStr) => {
    if (!timeStr) return '';
    const parts = timeStr.split(':');
    const h = parseInt(parts[0], 10);
    const m = parts[1] !== undefined ? parts[1] : '00';
    if (isNaN(h)) return timeStr;
    const period = h >= 12 ? 'PM' : 'AM';
    const displayHour = h % 12 === 0 ? 12 : h % 12;
    return `${displayHour}:${m} ${period}`;
};

export const formatTimeRange12 = (startTime, endTime) => {
    if (!startTime) return '';
    if (!endTime) return formatTime12(startTime);
    return `${formatTime12(startTime)} – ${formatTime12(endTime)}`;
};

export const BOOKING_STATUS = {
    PENDING: 'PENDING',
    AWAITING_PAYMENT: 'AWAITING_PAYMENT',
    PAID: 'PAID',
    CONFIRMED: 'CONFIRMED',
    CHECKED_IN: 'CHECKED_IN',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    EXPIRED: 'EXPIRED',
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    MAINTENANCE: 'MAINTENANCE',
};

export const BOOKING_SOURCE = {
    ONLINE: 'ONLINE',
    WALK_IN: 'WALK_IN',
    STAFF: 'STAFF',
};

export const PAYMENT_METHODS = [
    { id: 'GCASH', label: 'GCash', color: '#007DFE' },
    { id: 'CASH', label: 'Cash (Over-the-counter)', color: '#10B981' },
    { id: 'MAYA', label: 'Maya', color: '#22C55E' },
    { id: 'QRPH', label: 'QR Ph (Any Banking App)', color: '#D6FF3F' },
    { id: 'CARD', label: 'Credit / Debit Card', color: '#6366F1' },
];

export const STATUS_CONFIG = {
    [BOOKING_STATUS.CONFIRMED]: {
        label: 'Confirmed',
        bg: 'bg-white',
        text: 'text-[#101F1A]',
        subtext: 'text-[#101F1A]/70',
        border: 'border-[#101F1A]/15 hover:border-[#101F1A]/40',
        pillBg: 'bg-[#101F1A]/8',
        pillText: 'text-[#101F1A] font-bold',
        dotColor: 'bg-[#101F1A]',
        shadow: 'shadow-subtle',
    },
    [BOOKING_STATUS.CHECKED_IN]: {
        label: 'Checked In',
        bg: 'bg-[#F0FDF4]',
        text: 'text-[#064E3B]',
        subtext: 'text-[#065F46]/80',
        border: 'border-emerald-300 hover:border-emerald-500',
        pillBg: 'bg-emerald-100',
        pillText: 'text-emerald-900 font-extrabold',
        dotColor: 'bg-[#10B981]',
        shadow: 'shadow-[0_2px_10px_rgba(16,185,129,0.12)]',
        isLive: true,
    },
    [BOOKING_STATUS.IN_PROGRESS]: {
        label: 'In Progress',
        bg: 'bg-[#F7FEE7]',
        text: 'text-[#101F1A]',
        subtext: 'text-[#101F1A]/80',
        border: 'border-[#84CC16] hover:border-[#65A30D]',
        pillBg: 'bg-[#D6FF3F]',
        pillText: 'text-[#101F1A] font-black uppercase tracking-wider',
        dotColor: 'bg-[#84CC16]',
        shadow: 'shadow-[0_2px_12px_rgba(214,255,63,0.3)]',
        isLive: true,
    },
    [BOOKING_STATUS.PAID]: {
        label: 'Paid',
        bg: 'bg-white',
        text: 'text-[#101F1A]',
        subtext: 'text-[#101F1A]/70',
        border: 'border-emerald-300 hover:border-emerald-500',
        pillBg: 'bg-emerald-50 border border-emerald-200',
        pillText: 'text-emerald-800 font-bold',
        dotColor: 'bg-[#10B981]',
        shadow: 'shadow-subtle',
    },
    [BOOKING_STATUS.AWAITING_PAYMENT]: {
        label: 'Hold',
        bg: 'bg-[#FFF7F5]',
        text: 'text-[#101F1A]',
        subtext: 'text-[#8C2815]',
        border: 'border-dashed border-[#FF5A36] hover:border-[#E04826]',
        pillBg: 'bg-[#FF5A36]',
        pillText: 'text-white font-black',
        dotColor: 'bg-[#FF5A36]',
        shadow: 'shadow-[0_2px_8px_rgba(255,90,54,0.15)]',
        isHold: true,
    },
    [BOOKING_STATUS.PENDING]: {
        label: 'Pending',
        bg: 'bg-[#FFFBEB]',
        text: 'text-[#78350F]',
        subtext: 'text-[#92400E]',
        border: 'border-amber-300 hover:border-amber-400',
        pillBg: 'bg-amber-100',
        pillText: 'text-amber-800 font-semibold',
        dotColor: 'bg-amber-500',
        shadow: 'shadow-subtle',
    },
    [BOOKING_STATUS.COMPLETED]: {
        label: 'Completed',
        bg: 'bg-[#F5F2EA]',
        text: 'text-[#101F1A]/75',
        subtext: 'text-[#101F1A]/50',
        border: 'border-[#101F1A]/12 hover:border-[#101F1A]/25',
        pillBg: 'bg-stone-200',
        pillText: 'text-[#101F1A]/70 font-medium',
        dotColor: 'bg-[#101F1A]/35',
        shadow: 'shadow-2xs',
    },
    [BOOKING_STATUS.CANCELLED]: {
        label: 'Cancelled',
        bg: 'bg-[#FAFAFA]',
        text: 'text-stone-500 line-through',
        subtext: 'text-stone-400',
        border: 'border-stone-300',
        pillBg: 'bg-stone-100',
        pillText: 'text-stone-500 font-medium',
        dotColor: 'bg-stone-400',
        shadow: 'shadow-2xs',
    },
    [BOOKING_STATUS.EXPIRED]: {
        label: 'Expired Hold',
        bg: 'bg-[#FAFAFA]',
        text: 'text-stone-500',
        subtext: 'text-stone-400',
        border: 'border-stone-300',
        pillBg: 'bg-stone-100',
        pillText: 'text-stone-500 font-medium',
        dotColor: 'bg-stone-400',
        shadow: 'shadow-2xs',
    },
    [BOOKING_STATUS.MAINTENANCE]: {
        label: 'Maintenance',
        bg: 'bg-[#FEF3C7]',
        text: 'text-amber-950',
        subtext: 'text-amber-800',
        border: 'border-amber-300',
        pillBg: 'bg-amber-200',
        pillText: 'text-amber-900 font-bold',
        dotColor: 'bg-amber-500',
        shadow: 'shadow-subtle',
        isMaintenance: true,
    },
};

export const SPORTS_CONFIG = {
    Badminton: {
        name: 'Badminton',
        color: '#D6FF3F',
        bgPill: 'bg-[#D6FF3F]/15 text-[#D6FF3F]',
    },
    Futsal: {
        name: 'Futsal',
        color: '#10B981',
        bgPill: 'bg-[#10B981]/15 text-[#10B981]',
    },
    Pickleball: {
        name: 'Pickleball',
        color: '#FF5A36',
        bgPill: 'bg-[#FF5A36]/15 text-[#FF5A36]',
    },
    Basketball: {
        name: 'Basketball',
        color: '#F59E0B',
        bgPill: 'bg-amber-500/15 text-amber-400',
    },
    Volleyball: {
        name: 'Volleyball',
        color: '#3B82F6',
        bgPill: 'bg-blue-500/15 text-blue-400',
    },
    'Table Tennis': {
        name: 'Table Tennis',
        color: '#A855F7',
        bgPill: 'bg-purple-500/15 text-purple-400',
    },
};

export const MOCK_FACILITY = {
    id: 1,
    name: 'Bogo Sports Center',
    slug: 'bogo-sports-center',
    city: 'Bogo City, Cebu',
    operatingHours: {
        open: '06:00',
        close: '23:00',
        startHour: 6,
        endHour: 23,
    },
};

export const MOCK_COURTS = [
    {
        id: 'court-1',
        name: 'Court 1 — Badminton',
        shortName: 'Court 1',
        sport: 'Badminton',
        surface: 'Maple Hardwood',
        indoor: true,
        hourlyRate: 450,
        status: 'AVAILABLE',
    },
    {
        id: 'court-2',
        name: 'Court 2 — Futsal',
        shortName: 'Court 2',
        sport: 'Futsal',
        surface: 'Synthetic Turf',
        indoor: true,
        hourlyRate: 850,
        status: 'AVAILABLE',
    },
    {
        id: 'court-3',
        name: 'Court 3 — Pickleball',
        shortName: 'Court 3',
        sport: 'Pickleball',
        surface: 'Cushioned Acrylic',
        indoor: false,
        hourlyRate: 400,
        status: 'AVAILABLE',
    },
    {
        id: 'court-4',
        name: 'Court 4 — Basketball / Volleyball',
        shortName: 'Court 4',
        sport: 'Basketball',
        surface: 'Polyurethane',
        indoor: true,
        hourlyRate: 750,
        status: 'AVAILABLE',
    },
    {
        id: 'court-5',
        name: 'Court 5 — Table Tennis',
        shortName: 'Court 5',
        sport: 'Table Tennis',
        surface: 'Indoor Taraflex',
        indoor: true,
        hourlyRate: 300,
        status: 'AVAILABLE',
    },
];

export const MOCK_KPIS = {
    bookingsToday: {
        label: 'Bookings Today',
        value: 28,
        delta: 14.3,
        deltaType: 'increase',
        polarity: 'higher-is-better',
        comparisonText: 'vs 24 yesterday',
        period: 'today',
    },
    courtUtilization: {
        label: 'Court Utilization',
        value: '76.8%',
        rawValue: 76.8,
        delta: 6.2,
        deltaType: 'increase',
        polarity: 'higher-is-better',
        comparisonText: 'vs 70.6% last week',
        period: 'peak: 5–9 PM',
    },
    cancellationRate: {
        label: 'No-Show / Cancel Rate',
        value: '2.4%',
        rawValue: 2.4,
        delta: -1.2,
        deltaType: 'decrease',
        polarity: 'lower-is-better', // negative delta is GOOD (green)!
        comparisonText: 'vs 3.6% last period',
        period: 'last 7 days',
    },
    revenueToday: {
        label: 'Revenue Today',
        value: '₱26,450',
        rawValue: 26450,
        delta: 18.5,
        deltaType: 'increase',
        polarity: 'higher-is-better',
        comparisonText: 'vs ₱22,300 last Tuesday',
        period: '18 online · 10 walk-in',
    },
};

// Initial bookings populated with domain richness
export const INITIAL_BOOKINGS = [
    {
        id: 'bk-101',
        reference: 'CS-BK-8901',
        courtId: 'court-1',
        customerName: 'Marcus Vance',
        customerPhone: '+63 917 555 0192',
        customerEmail: 'marcus.v@gmail.com',
        initials: 'MV',
        sport: 'Badminton',
        startTime: '08:00',
        endTime: '09:30',
        durationHours: 1.5,
        status: BOOKING_STATUS.COMPLETED,
        source: BOOKING_SOURCE.ONLINE,
        paymentStatus: 'PAID',
        paymentMethod: 'GCASH',
        amount: 675,
        notes: 'Requested 2 extra Yonex rackets at front desk.',
    },
    {
        id: 'bk-102',
        reference: 'CS-BK-8902',
        courtId: 'court-1',
        customerName: 'Coach Alvin Tan',
        customerPhone: '+63 928 443 1188',
        customerEmail: 'alvin.tan@smashacademy.ph',
        initials: 'AT',
        sport: 'Badminton',
        startTime: '10:00',
        endTime: '12:00',
        durationHours: 2,
        status: BOOKING_STATUS.PAID,
        source: BOOKING_SOURCE.STAFF,
        paymentStatus: 'PAID',
        paymentMethod: 'CASH',
        amount: 900,
        notes: 'Junior squad training session. Paid in cash at reception.',
    },
    {
        id: 'bk-103',
        reference: 'CS-BK-8903',
        courtId: 'court-1',
        customerName: 'Bea Alonzo & Friends',
        customerPhone: '+63 917 888 2390',
        customerEmail: 'bea.alonzo@icloud.com',
        initials: 'BA',
        sport: 'Badminton',
        startTime: '13:00',
        endTime: '14:30',
        durationHours: 1.5,
        status: BOOKING_STATUS.IN_PROGRESS,
        source: BOOKING_SOURCE.ONLINE,
        paymentStatus: 'PAID',
        paymentMethod: 'MAYA',
        amount: 675,
        notes: 'Online booking via Maya. Checked in at 12:55 PM.',
    },
    {
        id: 'bk-104',
        reference: 'CS-BK-8904',
        courtId: 'court-1',
        customerName: 'Ramon Bautista',
        customerPhone: '+63 908 777 4321',
        customerEmail: 'ramon.b@yahoo.com',
        initials: 'RB',
        sport: 'Badminton',
        startTime: '15:00',
        endTime: '16:00',
        durationHours: 1,
        status: BOOKING_STATUS.CONFIRMED,
        source: BOOKING_SOURCE.ONLINE,
        paymentStatus: 'PAID',
        paymentMethod: 'GCASH',
        amount: 450,
        notes: 'Ready for check-in upon arrival.',
    },
    {
        id: 'bk-105',
        reference: 'CS-BK-8905',
        courtId: 'court-1',
        customerName: 'Walk-in: Kenneth Dee',
        customerPhone: '+63 919 222 9901',
        customerEmail: '',
        initials: 'KD',
        sport: 'Badminton',
        startTime: '17:00',
        endTime: '18:30',
        durationHours: 1.5,
        status: BOOKING_STATUS.AWAITING_PAYMENT,
        source: BOOKING_SOURCE.WALK_IN,
        paymentStatus: 'PENDING',
        paymentMethod: 'CASH',
        amount: 675,
        holdRemainingSeconds: 460, // ~7.5 mins
        notes: 'Staff holding slot while customer gets cash from ATM.',
    },
    {
        id: 'bk-106',
        reference: 'CS-BK-8906',
        courtId: 'court-1',
        customerName: 'Ateneo Alumni Club',
        customerPhone: '+63 917 111 8899',
        customerEmail: 'sports@ateneoalumni.ph',
        initials: 'AA',
        sport: 'Badminton',
        startTime: '19:00',
        endTime: '21:00',
        durationHours: 2,
        status: BOOKING_STATUS.CONFIRMED,
        source: BOOKING_SOURCE.ONLINE,
        paymentStatus: 'PAID',
        paymentMethod: 'CARD',
        amount: 900,
        notes: 'Corporate weekly club reservation.',
    },
    // Court 2 (Futsal)
    {
        id: 'bk-201',
        reference: 'CS-BK-8920',
        courtId: 'court-2',
        customerName: 'Bogo FC Prime',
        customerPhone: '+63 920 333 4455',
        customerEmail: 'bogofc@sports.ph',
        initials: 'BF',
        sport: 'Futsal',
        startTime: '07:00',
        endTime: '09:00',
        durationHours: 2,
        status: BOOKING_STATUS.COMPLETED,
        source: BOOKING_SOURCE.STAFF,
        paymentStatus: 'PAID',
        paymentMethod: 'CASH',
        amount: 1700,
        notes: 'Morning scrimmage practice.',
    },
    {
        id: 'bk-202',
        reference: 'CS-BK-8921',
        courtId: 'court-2',
        customerName: 'Cebu United Youth',
        customerPhone: '+63 917 444 7788',
        customerEmail: 'info@cebuunited.com',
        initials: 'CU',
        sport: 'Futsal',
        startTime: '10:00',
        endTime: '12:00',
        durationHours: 2,
        status: BOOKING_STATUS.CHECKED_IN,
        source: BOOKING_SOURCE.ONLINE,
        paymentStatus: 'PAID',
        paymentMethod: 'GCASH',
        amount: 1700,
        notes: 'Youth academy tournament preparation.',
    },
    {
        id: 'bk-203',
        reference: 'CS-BK-8922',
        courtId: 'court-2',
        customerName: 'Court 2 Maintenance — Turf Grooming & Line Repaint',
        customerPhone: 'Facility Operations',
        customerEmail: 'ops@courtsync.ph',
        initials: 'OP',
        sport: 'Futsal',
        startTime: '13:00',
        endTime: '15:30',
        durationHours: 2.5,
        status: BOOKING_STATUS.MAINTENANCE,
        source: BOOKING_SOURCE.STAFF,
        paymentStatus: 'N/A',
        paymentMethod: 'N/A',
        amount: 0,
        notes: 'Scheduled synthetic turf brushing and high-durability line touch-up.',
    },
    {
        id: 'bk-204',
        reference: 'CS-BK-8923',
        courtId: 'court-2',
        customerName: 'Red Bull Futsal 5s',
        customerPhone: '+63 918 999 1234',
        customerEmail: 'events@redbull.ph',
        initials: 'RB',
        sport: 'Futsal',
        startTime: '16:00',
        endTime: '18:00',
        durationHours: 2,
        status: BOOKING_STATUS.CONFIRMED,
        source: BOOKING_SOURCE.ONLINE,
        paymentStatus: 'PAID',
        paymentMethod: 'CARD',
        amount: 1700,
        notes: 'Qualifier team practice match.',
    },
    {
        id: 'bk-205',
        reference: 'CS-BK-8924',
        courtId: 'court-2',
        customerName: 'Walk-in: Team Barangay San Roque',
        customerPhone: '+63 915 332 1099',
        customerEmail: '',
        initials: 'SR',
        sport: 'Futsal',
        startTime: '18:30',
        endTime: '20:00',
        durationHours: 1.5,
        status: BOOKING_STATUS.AWAITING_PAYMENT,
        source: BOOKING_SOURCE.WALK_IN,
        paymentStatus: 'PENDING',
        paymentMethod: 'GCASH',
        amount: 1275,
        holdRemainingSeconds: 290, // ~4.8 mins
        notes: 'QR code generated at front desk. Waiting for GCash payment push.',
    },
    {
        id: 'bk-206',
        reference: 'CS-BK-8925',
        courtId: 'court-2',
        customerName: 'Midnight Futsal League',
        customerPhone: '+63 922 888 7766',
        customerEmail: 'league@cebusports.com',
        initials: 'ML',
        sport: 'Futsal',
        startTime: '20:30',
        endTime: '22:30',
        durationHours: 2,
        status: BOOKING_STATUS.CONFIRMED,
        source: BOOKING_SOURCE.ONLINE,
        paymentStatus: 'PAID',
        paymentMethod: 'QRPH',
        amount: 1700,
        notes: 'Weekly amateur league division finals.',
    },
    // Court 3 (Pickleball)
    {
        id: 'bk-301',
        reference: 'CS-BK-8930',
        courtId: 'court-3',
        customerName: 'Dra. Patricia Lim',
        customerPhone: '+63 917 654 3210',
        customerEmail: 'patricia.lim@medcebu.com',
        initials: 'PL',
        sport: 'Pickleball',
        startTime: '06:30',
        endTime: '08:00',
        durationHours: 1.5,
        status: BOOKING_STATUS.COMPLETED,
        source: BOOKING_SOURCE.ONLINE,
        paymentStatus: 'PAID',
        paymentMethod: 'MAYA',
        amount: 600,
        notes: 'Early morning singles session.',
    },
    {
        id: 'bk-302',
        reference: 'CS-BK-8931',
        courtId: 'court-3',
        customerName: 'Bogo Dinking Club',
        customerPhone: '+63 906 123 4567',
        customerEmail: 'bogodinkers@gmail.com',
        initials: 'BD',
        sport: 'Pickleball',
        startTime: '08:30',
        endTime: '11:00',
        durationHours: 2.5,
        status: BOOKING_STATUS.PAID,
        source: BOOKING_SOURCE.STAFF,
        paymentStatus: 'PAID',
        paymentMethod: 'CASH',
        amount: 1000,
        notes: 'Doubles rotation round-robin. 8 players on court.',
    },
    {
        id: 'bk-303',
        reference: 'CS-BK-8932',
        courtId: 'court-3',
        customerName: 'Carlos & Maya Yulo',
        customerPhone: '+63 919 789 0123',
        customerEmail: 'carlos.y@outlook.com',
        initials: 'CY',
        sport: 'Pickleball',
        startTime: '14:00',
        endTime: '15:30',
        durationHours: 1.5,
        status: BOOKING_STATUS.CONFIRMED,
        source: BOOKING_SOURCE.ONLINE,
        paymentStatus: 'PAID',
        paymentMethod: 'GCASH',
        amount: 600,
        notes: 'Court reservation confirmed. Rented 4 Franklin balls.',
    },
    {
        id: 'bk-304',
        reference: 'CS-BK-8933',
        courtId: 'court-3',
        customerName: 'Atty. Victor Consunji',
        customerPhone: '+63 917 333 4411',
        customerEmail: 'victor.c@lawfirm.ph',
        initials: 'VC',
        sport: 'Pickleball',
        startTime: '16:00',
        endTime: '18:00',
        durationHours: 2,
        status: BOOKING_STATUS.CONFIRMED,
        source: BOOKING_SOURCE.ONLINE,
        paymentStatus: 'PAID',
        paymentMethod: 'CARD',
        amount: 800,
        notes: 'Evening VIP reservation with spotlight usage included.',
    },
    {
        id: 'bk-305',
        reference: 'CS-BK-8934',
        courtId: 'court-3',
        customerName: 'Walk-in: Sarah Geronimo',
        customerPhone: '+63 920 111 2233',
        customerEmail: '',
        initials: 'SG',
        sport: 'Pickleball',
        startTime: '18:30',
        endTime: '20:00',
        durationHours: 1.5,
        status: BOOKING_STATUS.AWAITING_PAYMENT,
        source: BOOKING_SOURCE.WALK_IN,
        paymentStatus: 'PENDING',
        paymentMethod: 'MAYA',
        amount: 600,
        holdRemainingSeconds: 540, // ~9 mins
        notes: 'Walk-in hold created by cashier. Scanning Maya QR code.',
    },
    // Court 4 (Basketball / Volleyball)
    {
        id: 'bk-401',
        reference: 'CS-BK-8940',
        courtId: 'court-4',
        customerName: 'Barangay Captain Lito Sy',
        customerPhone: '+63 917 222 3344',
        customerEmail: 'brgy.poblacion@bogo.gov.ph',
        initials: 'LS',
        sport: 'Basketball',
        startTime: '06:00',
        endTime: '08:00',
        durationHours: 2,
        status: BOOKING_STATUS.COMPLETED,
        source: BOOKING_SOURCE.STAFF,
        paymentStatus: 'PAID',
        paymentMethod: 'CASH',
        amount: 1500,
        notes: 'Barangay seniors open morning run.',
    },
    {
        id: 'bk-402',
        reference: 'CS-BK-8941',
        courtId: 'court-4',
        customerName: 'Lady Spikers Club',
        customerPhone: '+63 918 444 5566',
        customerEmail: 'spikers@volleyballcebu.ph',
        initials: 'LS',
        sport: 'Volleyball',
        startTime: '09:00',
        endTime: '11:00',
        durationHours: 2,
        status: BOOKING_STATUS.PAID,
        source: BOOKING_SOURCE.ONLINE,
        paymentStatus: 'PAID',
        paymentMethod: 'GCASH',
        amount: 1500,
        notes: 'Volleyball net setup requested at 8:45 AM.',
    },
    {
        id: 'bk-403',
        reference: 'CS-BK-8942',
        courtId: 'court-4',
        customerName: 'Hoop Dreams Cebu Academy',
        customerPhone: '+63 922 555 6677',
        customerEmail: 'coach@hoopdreamscebu.com',
        initials: 'HD',
        sport: 'Basketball',
        startTime: '13:00',
        endTime: '16:00',
        durationHours: 3,
        status: BOOKING_STATUS.CONFIRMED,
        source: BOOKING_SOURCE.STAFF,
        paymentStatus: 'PAID',
        paymentMethod: 'CASH',
        amount: 2250,
        notes: '3-hour youth basketball clinic with 16 registered participants.',
    },
    {
        id: 'bk-404',
        reference: 'CS-BK-8943',
        courtId: 'court-4',
        customerName: 'Bogo Inter-Company Basketball',
        customerPhone: '+63 917 999 0011',
        customerEmail: 'league@cebubusiness.ph',
        initials: 'BI',
        sport: 'Basketball',
        startTime: '17:00',
        endTime: '20:00',
        durationHours: 3,
        status: BOOKING_STATUS.CONFIRMED,
        source: BOOKING_SOURCE.ONLINE,
        paymentStatus: 'PAID',
        paymentMethod: 'CARD',
        amount: 2250,
        notes: 'Doubleheader corporate league game with electronic scoreboard.',
    },
    // Court 5 (Table Tennis)
    {
        id: 'bk-501',
        reference: 'CS-BK-8950',
        courtId: 'court-5',
        customerName: 'Prof. Ernesto Rivera',
        customerPhone: '+63 919 444 3322',
        customerEmail: 'ernesto.rivera@cit.edu.ph',
        initials: 'ER',
        sport: 'Table Tennis',
        startTime: '08:00',
        endTime: '10:00',
        durationHours: 2,
        status: BOOKING_STATUS.COMPLETED,
        source: BOOKING_SOURCE.ONLINE,
        paymentStatus: 'PAID',
        paymentMethod: 'GCASH',
        amount: 600,
        notes: 'Table 1 air-conditioned room reserved.',
    },
    {
        id: 'bk-502',
        reference: 'CS-BK-8951',
        courtId: 'court-5',
        customerName: 'Spin Masters Club',
        customerPhone: '+63 917 888 9900',
        customerEmail: 'spinmasters@pingpong.ph',
        initials: 'SM',
        sport: 'Table Tennis',
        startTime: '11:00',
        endTime: '13:00',
        durationHours: 2,
        status: BOOKING_STATUS.CHECKED_IN,
        source: BOOKING_SOURCE.STAFF,
        paymentStatus: 'PAID',
        paymentMethod: 'CASH',
        amount: 600,
        notes: 'Robot feeder machine rented for 1 hour.',
    },
    {
        id: 'bk-503',
        reference: 'CS-BK-8952',
        courtId: 'court-5',
        customerName: 'Walk-in: Joshua & Mateo Garcia',
        customerPhone: '+63 928 123 7890',
        customerEmail: '',
        initials: 'JG',
        sport: 'Table Tennis',
        startTime: '14:30',
        endTime: '16:00',
        durationHours: 1.5,
        status: BOOKING_STATUS.CONFIRMED,
        source: BOOKING_SOURCE.WALK_IN,
        paymentStatus: 'PAID',
        paymentMethod: 'GCASH',
        amount: 450,
        notes: 'Paid via GCash counter QR scan.',
    },
    {
        id: 'bk-504',
        reference: 'CS-BK-8953',
        courtId: 'court-5',
        customerName: 'Cebu Table Tennis Open Qualifiers',
        customerPhone: '+63 917 555 4433',
        customerEmail: 'qualifiers@tabletenniscebu.ph',
        initials: 'CT',
        sport: 'Table Tennis',
        startTime: '17:00',
        endTime: '21:00',
        durationHours: 4,
        status: BOOKING_STATUS.CONFIRMED,
        source: BOOKING_SOURCE.ONLINE,
        paymentStatus: 'PAID',
        paymentMethod: 'CARD',
        amount: 1200,
        notes: 'Qualifying bracket matches.',
    },
];

export const INITIAL_EXPIRED_HOLDS = [
    {
        id: 'exp-1',
        reference: 'CS-BK-8890',
        customerName: 'Daniel Padilla',
        customerPhone: '+63 917 555 9988',
        customerEmail: 'daniel.p@gmail.com',
        initials: 'DP',
        courtName: 'Court 1 — Badminton',
        sport: 'Badminton',
        timeRange: '14:30 – 15:30',
        amount: 450,
        expiredAgo: '12m ago',
        reason: '30-minute PayMongo payment window elapsed',
    },
    {
        id: 'exp-2',
        reference: 'CS-BK-8891',
        customerName: 'Jaime Santos',
        customerPhone: '+63 908 444 3322',
        customerEmail: 'jaime.s@yahoo.com',
        initials: 'JS',
        courtName: 'Court 3 — Pickleball',
        sport: 'Pickleball',
        timeRange: '12:00 – 13:30',
        amount: 600,
        expiredAgo: '45m ago',
        reason: 'Customer cancelled checkout',
    },
];
